### PR TITLE
Upgrade to v1.6.0

### PR DESCRIPTION
**Pull request by ivangonzalezacuna**
Upgrade dependencies to v1.6.0, so we can use it in the next release of backstage (currently in progress)

### CODE REVIEW

**Comment by ivangonzalezacuna** [comment]
Don't approve yet. I need to remove the `@types/jest`, and also figure out what is the best approach to do the migration. As some internal packages already have migrated, now the tests complain about the `react-router-dom` not being found.

**Comment by heyLu** [comment]
> Don't approve yet. I need to remove the `@types/jest`, and also figure out what is the best approach to do the migration. As some internal packages already have migrated, now the tests complain about the `react-router-dom` not being found.

Ok!  We should probably also wait until we're ready to release 1.6.0 internally because otherwise we couldn't release update to this package until our internal instance is also updated.

**Comment by ivangonzalezacuna** [comment]
I have pushed the changes. I updated the submodule locally to use this branch and works as expected. I had to add the `react-router-dom` devDependency so that the tests pass, but I asked in the discoerd channel, in case there's another way to do it.

In case we need to keep it like that, we could push it, and then update the gitmodule, until then we will keep using the plugin with the version 1.5.1

**Review by heyLu — APPROVED** [review]
Approving now.  I missed that this was the grafana plugin not the s3 one, so it's less likely we need to change something in here before 1.6.0.

**Pull request merged**
