### PR TITLE
Backstage 1.20.2

### PR DESCRIPTION
**Pull request by ivangonzalezacuna**
Also nothing really important changed here so far.

Still waiting for the new repo to be created, once that is done, we can finally get rid of our fork :smile:

### CODE REVIEW

**Review by heyLu — APPROVED** [review]
Changes look good, but the title of the MR + commit is wrong, please change it to `1.20.2` to avoid confusion! :)

**Comment by heyLu** [comment]
> Still waiting for the new repo to be created, once that is done, we can finally get rid of our fork 😄

Did anyone sign up to do that, I thought someone still needs to volunteer to do that?

**Comment by ivangonzalezacuna** [comment]
> Changes look good, but the title of the MR + commit is wrong, please change it to `1.20.2` to avoid confusion! :)

I wanted to rename the branch as well (but I failed because I ended up creating a different MR :()

I'll just update the commit here and merge

**Comment by ivangonzalezacuna** [comment]
> > Still waiting for the new repo to be created, once that is done, we can finally get rid of our fork 😄
> 
> Did anyone sign up to do that, I thought someone still needs to volunteer to do that?

There was a person who said he would do it, but still waiting for him to create the repo and publish it

**Pull request merged**
