### PR TITLE
Bump to backstage 1.18.1

### PR DESCRIPTION
**Pull request by ivangonzalezacuna**
Also added the sideEffects flag in the package.json file, as suggested upstream.

No changes in the upstream plugin. Not touched for already 6 months... So annoying

### CODE REVIEW

**Comment by heyLu** [comment]
> Also added the sideEffects flag in the package.json file, as suggested upstream.

Did not know about the flag, here are some links about it: https://github.com/backstage/backstage/blob/master/docs/releases/v1.18.0.md#yarn-fix-and-sideeffects-false & https://github.com/webpack/webpack/blob/0b13cf19a19fd64d176c77aecbbf00ec57966276/examples/side-effects/README.md.  It seems it's an option for webpack that allows it to optimize packages if they only export things and don't do weird (stateful) things on import.

Did you add it via the new `yarn fix` command?

> No changes in the upstream plugin. Not touched for already 6 months... So annoying

Yes.  If you want maybe ask in Discord if some people/companies want to collaborate on a fork/replacement for the plugin?  At this point it's unfortunately a bit of a history with the author of the plugin.  And for the GitLab plugin the new fork has been much more active, so maybe this can be done here as well.

**Review by heyLu — APPROVED** [review]

**Comment by ivangonzalezacuna** [comment]
> Did not know about the flag, here are some links about it: https://github.com/backstage/backstage/blob/master/docs/releases/v1.18.0.md#yarn-fix-and-sideeffects-false & https://github.com/webpack/webpack/blob/0b13cf19a19fd64d176c77aecbbf00ec57966276/examples/side-effects/README.md. It seems it's an option for webpack that allows it to optimize packages if they only export things and don't do weird (stateful) things on import.
>
> Did you add it via the new `yarn fix` command?

Yes, I did a `yarn fix`, as in our backstage instance, to fix it automatically. It seems to be an initial change for a migration to a new backend start process. In the release they explain there's an experimental flag we could use

> Yes. If you want maybe ask in Discord if some people/companies want to collaborate on a fork/replacement for the plugin? At this point it's unfortunately a bit of a history with the author of the plugin. And for the GitLab plugin the new fork has been much more active, so maybe this can be done here as well.

I will do that. I've recently seen some messages in Discord about that plugin. Maybe we can opensource it or someone else is willing to add it as part of backstage (which would be the best option in my opinion)

**Comment by heyLu** [comment]
> It seems to be an initial change for a migration to a new backend start process. In the release they explain there's an experimental flag we could use

I'm pretty sure that the `sideEffects` parameter only applies to frontend projects and the new backend system is independent of that?  https://github.com/backstage/backstage/blob/master/docs/releases/v1.18.0.md#backend-system-ready-for-use

But nevermind, this PR looks good and we should probably try the new backend system/startup thing at some point soon.

**Comment by ivangonzalezacuna** [comment]
> I'm pretty sure that the `sideEffects` parameter only applies to frontend projects and the new backend system is independent of that? https://github.com/backstage/backstage/blob/master/docs/releases/v1.18.0.md#backend-system-ready-for-use
> 
> But nevermind, this PR looks good and we should probably try the new backend system/startup thing at some point soon.

Yes yes, there are 2 different things but I think kind of connected, because they want to improve the whole system.

Also, they have also started working in the new frontend system, which is similar to the new backend-system, which we should start migrating things to.

**Pull request merged**
